import { StatusPreview } from './credit';
import { MatchStatus, PlayeStatus, PlayerType } from './liveMatch';
import { MatchFormat } from './upcoming';

export type PointsType = {
  metrics: {
    key: string;
    help_text: string;
  }[];
  points: {
    player_key: string;
    rank: number;
    points: number;
    points_str: string | null;
    points_breakup: {
      metric_rule_index: number;
      points: number;
      points_str: string | null;
    }[];
    tournament_points: number;
  }[];

  players: {
    [key: string]: {
      key: string;
      name: string;
      jersey_name: string;
      legal_name: string;
      gender: 'male' | 'female';

      nationality: {
        short_code: string;
        code: string;
        name: string;
        official_name: string;
        is_region: boolean;
      };
      date_of_birth: number | null;
      team_key: string;
      seasonal_role: PlayerType;
    };
  };
  teams: {
    [key: string]: {
      key: string;
      code: string;
      name: string;
    };
  };
  match: {
    status_overview: StatusPreview;
    status: MatchStatus;
    match_meta: {
      key: string;
      status: MatchStatus;
      format: MatchFormat;
      start_at: number;
      status_overview: PlayeStatus;
    };
  };
};

export const pointsForTest: PointsType = {
  metrics: [
    {
      key: 'cricket_for_every_run',
      help_text: 'For every run scored by batsman',
    },
    {
      key: 'cricket_for_every_four',
      help_text: 'For every four scored by batsman',
    },
    {
      key: 'cricket_for_every_six',
      help_text: 'For every six scored by batsman',
    },
    {
      key: 'cricket_fifty_runs',
      help_text: 'For fifty runs scored by batsman',
    },
    {
      key: 'cricket_hundred_runs',
      help_text: 'For hundred runs scored by batsman',
    },
    {
      key: 'cricket_duck_runs',
      help_text: 'For zero run scored by batsman',
    },
    {
      key: 'cricket_for_every_wicket',
      help_text: 'For every wicket took by bowler',
    },
    {
      key: 'cricket_four_wickets',
      help_text: 'For four wickets took by bowler',
    },
    {
      key: 'cricket_five_wickets',
      help_text: 'For five wickets took by bowler',
    },
    {
      key: 'cricket_for_every_maiden_over',
      help_text: 'For every maiden over bowled by bowler',
    },
    {
      key: 'cricket_for_every_catch',
      help_text: 'For every catch by a fielder',
    },
    {
      key: 'cricket_for_every_stumping',
      help_text: 'For every stumping by a fielder',
    },
    {
      key: 'cricket_for_every_runout',
      help_text: 'For every runout scored by a fielder',
    },
    {
      key: 'cricket_economy_rate',
      help_text: 'For economy rate by a bowler',
    },
    {
      key: 'cricket_strike_rate',
      help_text: 'For strike rate by batsman',
    },
  ],
  points: [
    {
      player_key: 's_dhawan',
      rank: 1,
      points: 17.5,
      points_str: null,
      points_breakup: [
        {
          metric_rule_index: 0,
          points: 15.0,
          points_str: null,
        },
        {
          metric_rule_index: 1,
          points: 2.5,
          points_str: null,
        },
      ],
      tournament_points: 190.0,
    },
    {
      player_key: 'm_short',
      rank: 2,
      points: 14.0,
      points_str: null,
      points_breakup: [
        {
          metric_rule_index: 0,
          points: 12.0,
          points_str: null,
        },
        {
          metric_rule_index: 1,
          points: 1.0,
          points_str: null,
        },
        {
          metric_rule_index: 2,
          points: 1.0,
          points_str: null,
        },
      ],
      tournament_points: 86.0,
    },
    {
      player_key: 'p_chawla',
      rank: 3,
      points: 10.0,
      points_str: null,
      points_breakup: [
        {
          metric_rule_index: 6,
          points: 10.0,
          points_str: null,
        },
      ],
      tournament_points: 160.0,
    },
    {
      player_key: 'i_kishan',
      rank: 4,
      points: 10.0,
      points_str: null,
      points_breakup: [
        {
          metric_rule_index: 10,
          points: 4.0,
          points_str: null,
        },
        {
          metric_rule_index: 11,
          points: 6.0,
          points_str: null,
        },
      ],
      tournament_points: 160.5,
    },
    {
      player_key: 'c__player__arshad_khan__9c18b',
      rank: 5,
      points: 9.0,
      points_str: null,
      points_breakup: [
        {
          metric_rule_index: 6,
          points: 10.0,
          points_str: null,
        },
        {
          metric_rule_index: 13,
          points: -1.0,
          points_str: null,
        },
      ],
      tournament_points: 57.5,
    },
    {
      player_key: 'ps_singh',
      rank: 6,
      points: 5.0,
      points_str: null,
      points_breakup: [
        {
          metric_rule_index: 0,
          points: 4.5,
          points_str: null,
        },
        {
          metric_rule_index: 1,
          points: 0.5,
          points_str: null,
        },
      ],
      tournament_points: 136.0,
    },
    {
      player_key: 'ls_livingstone',
      rank: 7,
      points: 3.0,
      points_str: null,
      points_breakup: [
        {
          metric_rule_index: 0,
          points: 3.0,
          points_str: null,
        },
      ],
      tournament_points: 72.5,
    },
    {
      player_key: 'tim_david',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 124.0,
    },
    {
      player_key: 'r_meredith',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 66.0,
    },
    {
      player_key: 'c_jordan',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 0.0,
    },
    {
      player_key: 'b_rajapaksa',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 44.5,
    },
    {
      player_key: 'c__player__hrithik_shokeen__f16ef',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 48.5,
    },
    {
      player_key: 's_raza',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 118.0,
    },
    {
      player_key: 'c__player__nehal_wadhera__a0519',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 51.0,
    },
    {
      player_key: 'ard_singh',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 148.0,
    },
    {
      player_key: 'as_tendulkar',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 36.5,
    },
    {
      player_key: 'r_dhawan',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 0.5,
    },
    {
      player_key: 'c__player__mohit_rathee__fcc3e',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: -2.5,
    },
    {
      player_key: 'rg_sharma',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 117.0,
    },
    {
      player_key: 'c__player__akash_madhwal__3af22',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 0.0,
    },
    {
      player_key: 'c__player__atharva_taide__9e8aa',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 79.0,
    },
    {
      player_key: 'c__player__tristan_stubbs__ff381',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: -0.5,
    },
    {
      player_key: 'c__player__nathan_ellis__1a190',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 75.5,
    },
    {
      player_key: 'j_behrendorff',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 81.5,
    },
    {
      player_key: 's_warrier',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 0.0,
    },
    {
      player_key: 'c__player__raghav_goyal__00852',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 0.0,
    },
    {
      player_key: 'cam_green',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 196.0,
    },
    {
      player_key: 'c__player__ramandeep_singh__10427',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 8.0,
    },
    {
      player_key: 'vis_vinoth',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 0.0,
    },
    {
      player_key: 'shah_khan',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 75.0,
    },
    {
      player_key: 'h_singh',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 49.0,
    },
    {
      player_key: 'jc_archer',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 22.5,
    },
    {
      player_key: 'har_brar',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 61.0,
    },
    {
      player_key: 'c__player__gurnoor_brar__fd1a7',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: -3.0,
    },
    {
      player_key: 'ji_sharma',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 139.5,
    },
    {
      player_key: 'k_rabada',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 45.0,
    },
    {
      player_key: 'c__player__tilak_varma__90ac7',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 169.0,
    },
    {
      player_key: 'vid_kaverappa',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 0.0,
    },
    {
      player_key: 'rah_chahar',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 36.0,
    },
    {
      player_key: 'c__player__kumar_kartikeya__29a67',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 20.0,
    },
    {
      player_key: 's_mulani',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 0.0,
    },
    {
      player_key: 'c__player__shivam_singh_s__51c3a',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 0.0,
    },
    {
      player_key: 'c__player__baltej_singh__0e825',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 0.0,
    },
    {
      player_key: 's_yadav',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 152.0,
    },
    {
      player_key: 'sam_curran',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 199.0,
    },
    {
      player_key: 'c__player__duan_jansen__448c9',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 15.0,
    },
    {
      player_key: 'c__player__dewald_brevis__930ba',
      rank: 8,
      points: 0.0,
      points_str: null,
      points_breakup: [],
      tournament_points: 0.0,
    },
  ],
  players: {
    tim_david: {
      key: 'tim_david',
      name: 'Timothy David',
      jersey_name: 'David',
      legal_name: 'Timothy David',
      gender: 'male',
      nationality: {
        short_code: 'AU',
        code: 'AUS',
        name: 'Australia',
        official_name: 'the Commonwealth of Australia',
        is_region: false,
      },
      date_of_birth: 826934400.0,
      team_key: 'mi',
      seasonal_role: 'batsman',
    },
    r_meredith: {
      key: 'r_meredith',
      name: 'Riley Meredith',
      jersey_name: 'Meredith',
      legal_name: 'Riley Meredith',
      gender: 'male',
      nationality: {
        short_code: 'AU',
        code: 'AUS',
        name: 'Australia',
        official_name: 'the Commonwealth of Australia',
        is_region: false,
      },
      date_of_birth: 835315200.0,
      team_key: 'mi',
      seasonal_role: 'bowler',
    },
    c_jordan: {
      key: 'c_jordan',
      name: 'Chris Jordan',
      jersey_name: 'Jordan',
      legal_name: 'Chris Jordan',
      gender: 'male',
      nationality: {
        short_code: 'GB',
        code: 'GBR',
        name: 'United Kingdom',
        official_name: 'United Kingdom of Great Britain and Northern Ireland',
        is_region: false,
      },
      date_of_birth: 591926400.0,
      team_key: 'mi',
      seasonal_role: 'bowler',
    },
    b_rajapaksa: {
      key: 'b_rajapaksa',
      name: 'Bhanuka Rajapaksa',
      jersey_name: 'Rajapaksa',
      legal_name: 'Bhanuka Rajapaksa',
      gender: 'male',
      nationality: {
        short_code: 'LK',
        code: 'LKA',
        name: 'Sri Lanka',
        official_name: 'Democratic Socialist Republic of Sri Lanka',
        is_region: false,
      },
      date_of_birth: 688262400.0,
      team_key: 'pbks',
      seasonal_role: 'batsman',
    },
    c__player__hrithik_shokeen__f16ef: {
      key: 'c__player__hrithik_shokeen__f16ef',
      name: 'Hrithik Shokeen',
      jersey_name: 'Shokeen',
      legal_name: 'Hrithik Shokeen',
      gender: 'male',
      nationality: {
        short_code: 'IN',
        code: 'IND',
        name: 'India',
        official_name: 'Republic of India',
        is_region: false,
      },
      date_of_birth: 966211200.0,
      team_key: 'mi',
      seasonal_role: 'all_rounder',
    },
    s_raza: {
      key: 's_raza',
      name: 'Sikandar Raza',
      jersey_name: 'Raza',
      legal_name: 'Sikandar Raza',
      gender: 'male',
      nationality: {
        short_code: 'ZW',
        code: 'ZWE',
        name: 'Zimbabwe',
        official_name: 'Republic of Zimbabwe',
        is_region: false,
      },
      date_of_birth: 514684800.0,
      team_key: 'pbks',
      seasonal_role: 'all_rounder',
    },
    c__player__nehal_wadhera__a0519: {
      key: 'c__player__nehal_wadhera__a0519',
      name: 'Nehal Wadhera',
      jersey_name: 'Wadhera',
      legal_name: 'Nehal Wadhera',
      gender: 'male',
      nationality: {
        short_code: 'IN',
        code: 'IND',
        name: 'India',
        official_name: 'Republic of India',
        is_region: false,
      },
      date_of_birth: 968025600.0,
      team_key: 'mi',
      seasonal_role: 'batsman',
    },
    ard_singh: {
      key: 'ard_singh',
      name: 'Arshdeep Singh',
      jersey_name: 'Singh',
      legal_name: 'Arshdeep Singh',
      gender: 'male',
      nationality: {
        short_code: 'IN',
        code: 'IND',
        name: 'India',
        official_name: 'Republic of India',
        is_region: false,
      },
      date_of_birth: 918172800.0,
      team_key: 'pbks',
      seasonal_role: 'bowler',
    },
    as_tendulkar: {
      key: 'as_tendulkar',
      name: 'Arjun Tendulkar',
      jersey_name: 'Tendulkar',
      legal_name: 'Arjun Tendulkar',
      gender: 'male',
      nationality: {
        short_code: 'IN',
        code: 'IND',
        name: 'India',
        official_name: 'Republic of India',
        is_region: false,
      },
      date_of_birth: 938131200.0,
      team_key: 'mi',
      seasonal_role: 'bowler',
    },
    r_dhawan: {
      key: 'r_dhawan',
      name: 'Rishi Dhawan',
      jersey_name: 'Dhawan',
      legal_name: 'Rishi Dhawan',
      gender: 'male',
      nationality: {
        short_code: 'IN',
        code: 'IND',
        name: 'India',
        official_name: 'Republic of India',
        is_region: false,
      },
      date_of_birth: 635385600.0,
      team_key: 'pbks',
      seasonal_role: 'all_rounder',
    },
    p_chawla: {
      key: 'p_chawla',
      name: 'Piyush Chawla',
      jersey_name: 'Chawla',
      legal_name: 'Piyush Chawla',
      gender: 'male',
      nationality: {
        short_code: 'IN',
        code: 'IND',
        name: 'India',
        official_name: 'Republic of India',
        is_region: false,
      },
      date_of_birth: 598924800.0,
      team_key: 'mi',
      seasonal_role: 'bowler',
    },
    c__player__mohit_rathee__fcc3e: {
      key: 'c__player__mohit_rathee__fcc3e',
      name: 'Mohit Rathee',
      jersey_name: 'Rathee',
      legal_name: 'Mohit Rathee',
      gender: 'male',
      nationality: {
        short_code: 'IN',
        code: 'IND',
        name: 'India',
        official_name: 'Republic of India',
        is_region: false,
      },
      date_of_birth: 916185600.0,
      team_key: 'pbks',
      seasonal_role: 'bowler',
    },
    rg_sharma: {
      key: 'rg_sharma',
      name: 'Rohit Sharma',
      jersey_name: 'Sharma',
      legal_name: 'Rohit Sharma',
      gender: 'male',
      nationality: {
        short_code: 'IN',
        code: 'IND',
        name: 'India',
        official_name: 'Republic of India',
        is_region: false,
      },
      date_of_birth: 546739200.0,
      team_key: 'mi',
      seasonal_role: 'batsman',
    },
    c__player__akash_madhwal__3af22: {
      key: 'c__player__akash_madhwal__3af22',
      name: 'Akash Madhwal',
      jersey_name: 'Madhwal',
      legal_name: 'Akash Madhwal',
      gender: 'male',
      nationality: {
        short_code: 'IN',
        code: 'IND',
        name: 'India',
        official_name: 'Republic of India',
        is_region: false,
      },
      date_of_birth: 754185600.0,
      team_key: 'mi',
      seasonal_role: 'bowler',
    },
    c__player__atharva_taide__9e8aa: {
      key: 'c__player__atharva_taide__9e8aa',
      name: 'Atharva Taide',
      jersey_name: 'Taide',
      legal_name: 'Atharva Taide',
      gender: 'male',
      nationality: {
        short_code: 'IN',
        code: 'IND',
        name: 'India',
        official_name: 'Republic of India',
        is_region: false,
      },
      date_of_birth: 956707200.0,
      team_key: 'pbks',
      seasonal_role: 'batsman',
    },
    c__player__tristan_stubbs__ff381: {
      key: 'c__player__tristan_stubbs__ff381',
      name: 'Tristan Stubbs',
      jersey_name: 'Stubbs',
      legal_name: 'Tristan Stubbs',
      gender: 'male',
      nationality: {
        short_code: 'ZA',
        code: 'ZAF',
        name: 'South Africa',
        official_name: 'Republic of South Africa',
        is_region: false,
      },
      date_of_birth: 966211200.0,
      team_key: 'mi',
      seasonal_role: 'keeper',
    },
    c__player__nathan_ellis__1a190: {
      key: 'c__player__nathan_ellis__1a190',
      name: 'Nathan Ellis',
      jersey_name: 'Ellis',
      legal_name: 'Nathan Ellis',
      gender: 'male',
      nationality: {
        short_code: 'AU',
        code: 'AUS',
        name: 'Australia',
        official_name: 'the Commonwealth of Australia',
        is_region: false,
      },
      date_of_birth: 780192000.0,
      team_key: 'pbks',
      seasonal_role: 'bowler',
    },
    m_short: {
      key: 'm_short',
      name: 'Matthew Short',
      jersey_name: 'Short',
      legal_name: 'Matthew Short',
      gender: 'male',
      nationality: {
        short_code: 'AU',
        code: 'AUS',
        name: 'Australia',
        official_name: 'the Commonwealth of Australia',
        is_region: false,
      },
      date_of_birth: 815788800.0,
      team_key: 'pbks',
      seasonal_role: 'all_rounder',
    },
    j_behrendorff: {
      key: 'j_behrendorff',
      name: 'Jason Behrendorff',
      jersey_name: 'Behrendorff',
      legal_name: 'Jason Behrendorff',
      gender: 'male',
      nationality: {
        short_code: 'AU',
        code: 'AUS',
        name: 'Australia',
        official_name: 'the Commonwealth of Australia',
        is_region: false,
      },
      date_of_birth: 640569600.0,
      team_key: 'mi',
      seasonal_role: 'bowler',
    },
    s_warrier: {
      key: 's_warrier',
      name: 'SS Warrier',
      jersey_name: 'Warrier',
      legal_name: 'SS Warrier',
      gender: 'male',
      nationality: {
        short_code: 'IN',
        code: 'IND',
        name: 'India',
        official_name: 'Republic of India',
        is_region: false,
      },
      date_of_birth: 670723200.0,
      team_key: 'mi',
      seasonal_role: 'bowler',
    },
    c__player__raghav_goyal__00852: {
      key: 'c__player__raghav_goyal__00852',
      name: 'Raghav Goyal',
      jersey_name: 'Goyal',
      legal_name: 'Raghav Goyal',
      gender: 'male',
      nationality: {
        short_code: 'IN',
        code: 'IND',
        name: 'India',
        official_name: 'Republic of India',
        is_region: false,
      },
      date_of_birth: 992995200.0,
      team_key: 'mi',
      seasonal_role: 'all_rounder',
    },
    ps_singh: {
      key: 'ps_singh',
      name: 'Prabhsimran Singh',
      jersey_name: 'Singh',
      legal_name: 'Prabhsimran Singh',
      gender: 'male',
      nationality: {
        short_code: 'IN',
        code: 'IND',
        name: 'India',
        official_name: 'Republic of India',
        is_region: false,
      },
      date_of_birth: 965865600.0,
      team_key: 'pbks',
      seasonal_role: 'keeper',
    },
    cam_green: {
      key: 'cam_green',
      name: 'Cameron Green',
      jersey_name: 'Green',
      legal_name: 'Cameron Green',
      gender: 'male',
      nationality: {
        short_code: 'AU',
        code: 'AUS',
        name: 'Australia',
        official_name: 'the Commonwealth of Australia',
        is_region: false,
      },
      date_of_birth: 928368000.0,
      team_key: 'mi',
      seasonal_role: 'all_rounder',
    },
    c__player__ramandeep_singh__10427: {
      key: 'c__player__ramandeep_singh__10427',
      name: 'Ramandeep Singh',
      jersey_name: 'Singh',
      legal_name: 'Ramandeep Singh',
      gender: 'male',
      nationality: {
        short_code: 'IN',
        code: 'IND',
        name: 'India',
        official_name: 'Republic of India',
        is_region: false,
      },
      date_of_birth: 860889600.0,
      team_key: 'mi',
      seasonal_role: 'all_rounder',
    },
    vis_vinoth: {
      key: 'vis_vinoth',
      name: 'Vishnu Vinod',
      jersey_name: 'Vinod',
      legal_name: 'Vishnu Vinod',
      gender: 'male',
      nationality: {
        short_code: 'IN',
        code: 'IND',
        name: 'India',
        official_name: 'Republic of India',
        is_region: false,
      },
      date_of_birth: 754790400.0,
      team_key: 'mi',
      seasonal_role: 'keeper',
    },
    shah_khan: {
      key: 'shah_khan',
      name: 'Shahrukh Khan',
      jersey_name: 'Khan',
      legal_name: 'Shahrukh Khan',
      gender: 'male',
      nationality: {
        short_code: 'IN',
        code: 'IND',
        name: 'India',
        official_name: 'Republic of India',
        is_region: false,
      },
      date_of_birth: 801532800.0,
      team_key: 'pbks',
      seasonal_role: 'batsman',
    },
    h_singh: {
      key: 'h_singh',
      name: 'Harpreet Singh',
      jersey_name: 'Singh',
      legal_name: 'Harpreet Singh',
      gender: 'male',
      nationality: {
        short_code: 'IN',
        code: 'IND',
        name: 'India',
        official_name: 'Republic of India',
        is_region: false,
      },
      date_of_birth: 681868800.0,
      team_key: 'pbks',
      seasonal_role: 'batsman',
    },
    jc_archer: {
      key: 'jc_archer',
      name: 'Jofra Archer',
      jersey_name: 'Archer',
      legal_name: 'Jofra Archer',
      gender: 'male',
      nationality: {
        short_code: 'GB',
        code: 'GBR',
        name: 'United Kingdom',
        official_name: 'United Kingdom of Great Britain and Northern Ireland',
        is_region: false,
      },
      date_of_birth: 796694400.0,
      team_key: 'mi',
      seasonal_role: 'bowler',
    },
    har_brar: {
      key: 'har_brar',
      name: 'Harpreet Brar',
      jersey_name: 'Brar',
      legal_name: 'Harpreet Brar',
      gender: 'male',
      nationality: {
        short_code: 'IN',
        code: 'IND',
        name: 'India',
        official_name: 'Republic of India',
        is_region: false,
      },
      date_of_birth: 811209600.0,
      team_key: 'pbks',
      seasonal_role: 'bowler',
    },
    c__player__gurnoor_brar__fd1a7: {
      key: 'c__player__gurnoor_brar__fd1a7',
      name: 'Gurnoor Brar',
      jersey_name: 'Brar',
      legal_name: 'Gurnoor Brar',
      gender: 'male',
      nationality: {
        short_code: 'IN',
        code: 'IND',
        name: 'India',
        official_name: 'Republic of India',
        is_region: false,
      },
      date_of_birth: 959212800.0,
      team_key: 'pbks',
      seasonal_role: 'bowler',
    },
    ji_sharma: {
      key: 'ji_sharma',
      name: 'Jitesh Sharma',
      jersey_name: 'Sharma',
      legal_name: 'Jitesh Sharma',
      gender: 'male',
      nationality: {
        short_code: 'IN',
        code: 'IND',
        name: 'India',
        official_name: 'Republic of India',
        is_region: false,
      },
      date_of_birth: 751248000.0,
      team_key: 'pbks',
      seasonal_role: 'keeper',
    },
    k_rabada: {
      key: 'k_rabada',
      name: 'Kagiso Rabada',
      jersey_name: 'Rabada',
      legal_name: 'Kagiso Rabada',
      gender: 'male',
      nationality: {
        short_code: 'ZA',
        code: 'ZAF',
        name: 'South Africa',
        official_name: 'Republic of South Africa',
        is_region: false,
      },
      date_of_birth: 801360000.0,
      team_key: 'pbks',
      seasonal_role: 'bowler',
    },
    s_dhawan: {
      key: 's_dhawan',
      name: 'Shikhar Dhawan',
      jersey_name: 'Dhawan',
      legal_name: 'Shikhar Dhawan',
      gender: 'male',
      nationality: {
        short_code: 'IN',
        code: 'IND',
        name: 'India',
        official_name: 'Republic of India',
        is_region: false,
      },
      date_of_birth: 502588800.0,
      team_key: 'pbks',
      seasonal_role: 'batsman',
    },
    c__player__tilak_varma__90ac7: {
      key: 'c__player__tilak_varma__90ac7',
      name: 'Tilak Varma',
      jersey_name: 'Varma',
      legal_name: 'Tilak Varma',
      gender: 'male',
      nationality: {
        short_code: 'IN',
        code: 'IND',
        name: 'India',
        official_name: 'Republic of India',
        is_region: false,
      },
      date_of_birth: 1036713600.0,
      team_key: 'mi',
      seasonal_role: 'batsman',
    },
    vid_kaverappa: {
      key: 'vid_kaverappa',
      name: 'Vidwath Kaverappa',
      jersey_name: 'Kaverappa',
      legal_name: 'Vidwath Kaverappa',
      gender: 'male',
      nationality: {
        short_code: 'IN',
        code: 'IND',
        name: 'India',
        official_name: 'Republic of India',
        is_region: false,
      },
      date_of_birth: 919900800.0,
      team_key: 'pbks',
      seasonal_role: 'bowler',
    },
    rah_chahar: {
      key: 'rah_chahar',
      name: 'Rahul Chahar',
      jersey_name: 'Chahar',
      legal_name: 'Rahul Chahar',
      gender: 'male',
      nationality: {
        short_code: 'IN',
        code: 'IND',
        name: 'India',
        official_name: 'Republic of India',
        is_region: false,
      },
      date_of_birth: 933724800.0,
      team_key: 'pbks',
      seasonal_role: 'bowler',
    },
    c__player__kumar_kartikeya__29a67: {
      key: 'c__player__kumar_kartikeya__29a67',
      name: 'Kumar Kartikeya',
      jersey_name: 'Kartikeya',
      legal_name: 'Kumar Kartikeya',
      gender: 'male',
      nationality: {
        short_code: 'IN',
        code: 'IND',
        name: 'India',
        official_name: 'Republic of India',
        is_region: false,
      },
      date_of_birth: 883094400.0,
      team_key: 'mi',
      seasonal_role: 'bowler',
    },
    i_kishan: {
      key: 'i_kishan',
      name: 'Ishan Kishan',
      jersey_name: 'Kishan',
      legal_name: 'Ishan Kishan',
      gender: 'male',
      nationality: {
        short_code: 'IN',
        code: 'IND',
        name: 'India',
        official_name: 'Republic of India',
        is_region: false,
      },
      date_of_birth: 900720000.0,
      team_key: 'mi',
      seasonal_role: 'keeper',
    },
    s_mulani: {
      key: 's_mulani',
      name: 'Shams Mulani',
      jersey_name: 'Mulani',
      legal_name: 'Shams Mulani',
      gender: 'male',
      nationality: {
        short_code: 'IN',
        code: 'IND',
        name: 'India',
        official_name: 'Republic of India',
        is_region: false,
      },
      date_of_birth: 858211200.0,
      team_key: 'mi',
      seasonal_role: 'bowler',
    },
    c__player__shivam_singh_s__51c3a: {
      key: 'c__player__shivam_singh_s__51c3a',
      name: 'Shivam Singh S',
      jersey_name: 'Singh',
      legal_name: 'Shivam Singh S',
      gender: 'male',
      nationality: {
        short_code: 'IN',
        code: 'IND',
        name: 'India',
        official_name: 'Republic of India',
        is_region: false,
      },
      date_of_birth: null,
      team_key: 'pbks',
      seasonal_role: 'batsman',
    },
    c__player__baltej_singh__0e825: {
      key: 'c__player__baltej_singh__0e825',
      name: 'Baltej Singh',
      jersey_name: 'Singh',
      legal_name: 'Baltej Singh',
      gender: 'male',
      nationality: {
        short_code: 'IN',
        code: 'IND',
        name: 'India',
        official_name: 'Republic of India',
        is_region: false,
      },
      date_of_birth: 657676800.0,
      team_key: 'pbks',
      seasonal_role: 'bowler',
    },
    ls_livingstone: {
      key: 'ls_livingstone',
      name: 'Liam Livingstone',
      jersey_name: 'Livingstone',
      legal_name: 'Liam Livingstone',
      gender: 'male',
      nationality: {
        short_code: 'GB',
        code: 'GBR',
        name: 'United Kingdom',
        official_name: 'United Kingdom of Great Britain and Northern Ireland',
        is_region: false,
      },
      date_of_birth: 744422400.0,
      team_key: 'pbks',
      seasonal_role: 'all_rounder',
    },
    s_yadav: {
      key: 's_yadav',
      name: 'Suryakumar Yadav',
      jersey_name: 'Yadav',
      legal_name: 'Suryakumar Yadav',
      gender: 'male',
      nationality: {
        short_code: 'IN',
        code: 'IND',
        name: 'India',
        official_name: 'Republic of India',
        is_region: false,
      },
      date_of_birth: 653270400.0,
      team_key: 'mi',
      seasonal_role: 'batsman',
    },
    sam_curran: {
      key: 'sam_curran',
      name: 'Sam Curran',
      jersey_name: 'Curran',
      legal_name: 'Sam Curran',
      gender: 'male',
      nationality: {
        short_code: 'GB',
        code: 'GBR',
        name: 'United Kingdom',
        official_name: 'United Kingdom of Great Britain and Northern Ireland',
        is_region: false,
      },
      date_of_birth: 896832000.0,
      team_key: 'pbks',
      seasonal_role: 'all_rounder',
    },
    c__player__duan_jansen__448c9: {
      key: 'c__player__duan_jansen__448c9',
      name: 'Duan Jansen',
      jersey_name: 'Jansen',
      legal_name: 'Duan Jansen',
      gender: 'male',
      nationality: {
        short_code: 'ZA',
        code: 'ZAF',
        name: 'South Africa',
        official_name: 'Republic of South Africa',
        is_region: false,
      },
      date_of_birth: 957139200.0,
      team_key: 'mi',
      seasonal_role: 'bowler',
    },
    c__player__arshad_khan__9c18b: {
      key: 'c__player__arshad_khan__9c18b',
      name: 'Arshad Khan',
      jersey_name: 'Khan',
      legal_name: 'Arshad Khan',
      gender: 'male',
      nationality: {
        short_code: 'IN',
        code: 'IND',
        name: 'India',
        official_name: 'Republic of India',
        is_region: false,
      },
      date_of_birth: 882576000.0,
      team_key: 'mi',
      seasonal_role: 'bowler',
    },
    c__player__dewald_brevis__930ba: {
      key: 'c__player__dewald_brevis__930ba',
      name: 'Dewald Brevis',
      jersey_name: 'Brevis',
      legal_name: 'Dewald Brevis',
      gender: 'male',
      nationality: {
        short_code: 'ZA',
        code: 'ZAF',
        name: 'South Africa',
        official_name: 'Republic of South Africa',
        is_region: false,
      },
      date_of_birth: 1051574400.0,
      team_key: 'mi',
      seasonal_role: 'batsman',
    },
  },
  teams: {
    pbks: {
      key: 'pbks',
      code: 'PBKS',
      name: 'Punjab Kings',
    },
    mi: {
      key: 'mi',
      code: 'MI',
      name: 'Mumbai Indians',
    },
  },
  match: {
    status_overview: 'in_play',
    status: 'started',
    match_meta: {
      key: 'iplt20_2023_g45',
      status: 'started',
      format: 't20',
      start_at: 1683122400.0,
      status_overview: 'in_play',
    },
  },
};
